[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000   
  port = 8888        
  functions = "netlify/functions"

